# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Symfony

on:
  push:
    branches: [ "main" ]

jobs:
  symfony-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@2cb9b829437ee246e9b3cac53555a39208ca6d28
        with:
          php-version: '8.4'
      - uses: actions/checkout@v4
      - name: Copy .env.test.local
        run: php -r "file_exists('.env.test.local') || copy('.env.test', '.env.test.local');"
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      - name: Install Dependencies
        run: composer install -qn --no-ansi --no-scripts --no-progress --prefer-dist
      - name: Execute tests
        run: vendor/bin/phpunit


  deploy:
    name: run pull
    runs-on: ubuntu-latest

    steps:
      - name: test
        run: | 

      - name: Checkout code
        uses: actions/checkout@v3

#      - name: Set up SSH
#        run: |
#          install -m 600 -D /dev/null ~/.ssh/id_rsa
#          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
#          ssh-keyscan -H ${{ secrets.SERVER_HOST }} > ~/.ssh/known_hosts

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /services/feast_calc
            git pull origin main
          
            # Create .env file from GitHub secrets
            cat > .env << EOL
            APP_ENV=prod
            FISCAL_TOKEN=${{ secrets.FISCAL_TOKEN }}
            EOL
            docker compose up -d --build --force-recreate
          

#
#      - name: Deploy to server
#        run: ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "cd /services/feast_calc && git pull origin main && docker compose up -d --build --force-recreate"
#      - name: cleanup
#        run: rm -rf ~/.ssh